[package]
name = "vexv5_serial"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
serialport = "4.2.0"
anyhow = "1.0.0"
crc = "3.0.0"
=======
ascii = "1.0.0"
serialport = "4.2.0"
anyhow = "1.0.0"
crc = "3.0.0"
chrono = "0.4"
corncobs = "0.1.1"
>>>>>>> master
bitflags = "1.3.2"
thiserror = "1.0.37"