[package]
name = "vexv5_serial"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "2.0.0-rc.1"
serialport = "4.2.0"
anyhow = "1.0.0"