[package]
name = "vex-v5-serial"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "A library for communicating with VEX V5 Brains"
repository = "https://github.com/vexide/vex-v5-serial"
authors = [
    "vexide",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "Tropical"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# We depend on this because for some reason it fixes an issue with tokio-serial.
serialport = "4.2.0"
tokio-serial = { version = "5.4.4", default-features = false }
tokio = { version = "1.23.0", features = ["full"] }
crc = "3.0.0"
thiserror = "1.0.37"
serde = { version = "1.0.203", features = ["derive"] }
serde_ini = "0.2.0"
bitflags = "2.5.0"
flate2 = "1.0.30"
log = "0.4.21"
uuid = "1.8.0"
serde_bytes = "0.11.15"
image = { version = "0.25.1", optional = true }
btleplug = { version = "0.11.5", optional = true }
tokio-stream = { version = "0.1.11", optional = true }
futures = { version = "0.3.30", optional = true }

[dev-dependencies]
simplelog = "0.12.2"
rustyline = "14.0.0"

[features]
default = ["bluetooth", "screen-command"]
bluetooth = ["dep:btleplug", "dep:futures", "dep:tokio-stream"]
screen-command = ["dep:image"]

# We do this so that tokio-serial uses the latest, fixed version of mio-serial
[patch.crates-io]
mio-serial = { git = "https://github.com/berkowski/mio-serial.git" }
