[package]
name = "vexv5_serial"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# We depend on this because for some reason it fixes an issue with tokio-serial.
serialport = "4.2.0"
tokio-serial = "5.4.4"
tokio = { version = "1.23.0", features = ["full"] }
tokio-stream = "0.1.11"
crc = "3.0.0"
thiserror = "1.0.37"
chrono = "0.4.38"
serde = { version = "1.0.203", features = ["derive"] }
serde_ini = "0.2.0"
bitflags = "2.5.0"
flate2 = "1.0.30"
log = "0.4.21"
image = "0.25.1"
uuid = "1.8.0"
btleplug = "0.11.5"

[dev-dependencies]
simplelog = "0.12.2"
rustyline = "14.0.0"

# We do this so that tokio-serial uses the latest, fixed version of mio-serial
[patch.crates-io]
mio-serial = { git="https://github.com/berkowski/mio-serial.git" }
